### ISSUE TITLE
Support choosing fourth and fifth buttons as gesture buttons

### ISSUE THREAD

**Issue by bluetech** [marklieberman/foxygestures#108]
Currently in the "Gesture Button" option of the extension, the choices offered are "Left", "Middle", "Right". However, there are two other possible buttons, "Fourth button" and "Fifth button" ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#Return_value), [example picture](http://product-images.www8-hp.com/digmedialib/prodimg/lowres/c02605547.png)). These buttons are normally used for browser back, browser forward.

The `BUTTONS` array in `mouseEvents.js` already defines constants for them, but `options.tab.general.html` is missing them. Can they be added?

Background: I am using Linux, and I used to FireGestures with the Right button. Because of the context menu problem this is no longer working, so I thought maybe one of these other buttons (which I currently don't use) might work out.

Thanks for working on this extension!

**Comment by marklieberman** [comment]
If you are willing to try, clone or download the addon locally and add the additional buttons to the select list in `options.tab.general.html`:
```
<option ng-value="3">Button 4</option>
<option ng-value="4">Button 5</option>
```
Then load the addon by going to about:debugging > Load Temporary Addon, and browse to `src/manifest.json`.

The reason I never added them to the list is because despite having buttons 4 and 5 on my mouse, I was never actually able to get mousedown events when pressing them. I don't know if it is a OS limitation.

**Comment by bluetech** [comment]
Indeed, it does not work :( The page for `buttons` also documents this for GTK: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons#Browser_compatibility

Guess I'll close this; thanks!
