### ISSUE TITLE
Issues with Surface

### ISSUE THREAD

**Issue by yulahuyed** [marklieberman/foxygestures#117]
This extension cannot use with touch on Surface. Both long press and pen don't work.
Also, some pages don't work. 
Like
new tab
about:****
https://addons.mozilla.org

**Comment by marklieberman** [comment]
I don't have a touch input device to test on. Also I know it doesn't work on about: pages. It says as much in the addon description. Web extensions don't have access to those pages.

**Comment by tmarkov** [comment]
I tested it on my Surface Book. Here's what I had:
Using left mouse button for gestures: Pen works. Double tap and drag works.
Using right mouse button for gestures: Pen works, so long as I press the "right click" button on the pen before I touch the screen with it. For some reason, if I first touch the screen, then press the right click button and start a gesture, it doesn't work. Long press doesn't work, since long press is interpreted (on my PC) as right button click and release, not click and hold.

**Comment by marklieberman** [comment]
See #217 instead. That issue has more information.
