### ISSUE TITLE
FoxyGestures works poorly on some livejournal.com pages

### ISSUE THREAD

**Issue by mikamiel** [marklieberman/foxygestures#140]
FoxyGestures works poorly on some livejournal.com pages. For example on http://tonsky.livejournal.com/
it is laggy, almost unusable.

**Comment by marklieberman** [comment]
If you block scripts with uBlock then it works fine. The problem is most likely a script included on that page that is also doing things with mouse events. I probably cannot resolve this because as a Web Extension I am sharing the JavaScript scope with the page.

**Comment by marklieberman** [comment]
The problem here is a video player script that is throwing exceptions due to the postMessage communication when a gesture is performed. To allow gestures to work seamlessly across iframes, mouse events from nested frames are sent to their parent frame, up until the top frame/window using postMessage.

Any script that listens to the 'message' event can receive the message. A proper listener should verify that the message received is an expected message, and ignore unexpected messages. The video player script is not checking that the message is expected, so my message are being processed and generating an exception.

If you notice, it doesn't seem to get laggy until you first perform a gesture. It is because when you perform a gesture it generates a burst of postMessage traffic.

**Comment by mikamiel** [comment]
Of course i use uBlock addon all the way ;)
The bad thing is that this issue appears on a lot of livejournal.com pages/blogs i visit every day.
By the way, after some testing, Gesturefy addon seems to be working fine on those sites.

**Comment by marklieberman** [comment]
Looks like Gesturefy is bouncing messages off of the background script (frame -> background -> tab) with runtime.sendMessage script to avoid using window.postMessage. Perhaps I'll do it the same way. postMessage is more direct but bouncing sendMessage has less interference with the page.

**Comment by marklieberman** [comment]
I found an easy solution that seems to have resolved this issue. 

It appears that the problem was there are multiple instances of hidden iframes running scripts on this page. Foxy Gestures is using postMessage to emit some 'stateUpdate' messages down the frame hierarchy to keep the gesture state on all frames in sync. The script in the hidden iframes was taking my stateUpdate message, and repeating it back to the top window. 

Since there are multiple hidden iframes the message would be repeated back to me multiple times. The stateUpdate message would then cascade down the hierarchy again, and be repeated again. Essentially it became like a postMessage storm. A simple check that the stateUpdate message came from the parent window seems to have resolved this.

**Comment by mikamiel** [comment]
Thanks, i'll try it.

**Comment by Mercury13** [comment]
Still no progress? LiveJournal is an important site of xUSSR.
