### ISSUE TITLE
Back to Start

### ISSUE THREAD

**Issue by cinke** [marklieberman/foxygestures#150]
Is it possible to create a script that brings you back to the first page on a site, after browsing on it?
Similar to this old plugin: https://github.com/gpayer/back-to-start

**Comment by marklieberman** [comment]
I cannot be done with a user script. The problem is that there is no way in regular JavaScript to know the history of a tab that includes the URLs. You could make a script that goes back to the first URL loaded in a tab like so:
```js
window.History.back(window.History.length - 1);
```
Without knowing the URLs though, its impossible to know how far back to go to get to the start of the current site.

Implemented using web extension APIs, you could monitor the history using browser.tabs.onChanged and keep track of the URLs manually. You can't install that listener from a user script because scripts are only run on demand.

Probably the best way is to make a web extension that tracks the tab history and invoke it from a user script using browser.runtime.onMessageExternal.
