### ISSUE TITLE
Mouse Chord to re-open closed tab pops-up context menu

### ISSUE THREAD

**Issue by rodalpho** [marklieberman/foxygestures#170]
Please see 164 for context.

https://github.com/marklieberman/foxygestures/issues/164

In short, I also bind the L+R chord to re-open the last closed tab-- and that does popup the context menu.

Testing on MacOS with FX58b5 and the contextmenu about:config flag set.

**Comment by marklieberman** [comment]
This is a similar situation to #144.

**Comment by marklieberman** [comment]
I'm working on this, but it turns out it's a little more difficult because there is a delay between the closed tab getting restored and the content scripts being injected into it that makes communication difficult.

**Comment by marklieberman** [comment]
This issue is very difficult to solve completely. There is fundamentally a problem that Foxy Gestures scripts are not injected until the page has loaded a little bit, so there is always a window where you can get the context menu to popup. I've got it working well enough as long as you aren't doing the Undo Close chord too fast.

**Comment by rodalpho** [comment]
Yes, it's much improved-- I've been using FoxyGestures on MacOS for some time now, switched back from Gesturefy, and haven't been hit by the context menu popping up recently.
