### ISSUE TITLE
Extension diables RMB context menu on framed pages in data:uri documents

### ISSUE THREAD

**Issue by myfonj** [marklieberman/foxygestures#190]
Steps to Reprduce:
1) With extension disabled or not installed, visit `data:text/html,<iframe src="http://example.org/">`.
2) Right mouse button click in frame → works OK: context menu opened.
3) Install or enable the extension and reload data:uri 'page'.
4) RMB: does nothing.

Nightly 59.0a1 Build ID 	20171218100313 Windows 10
Foxy Gestures 1.0.15

**Comment by marklieberman** [comment]
Confirmed on FF57 on Windows, but seems to work on OSX.

**Comment by marklieberman** [comment]
This was happening because FF doesn't inject content_scripts into data:uri documents, but does inject into the example.org iframe. The content_script in the iframe was expecting to talk to the top-level content_script but it wasn't there, so communication broke down.

Since faca06c1b152cd189e77b4b8f58cf3f13e6cbd0d, FG doesn't install mouse event handlers in any frames until the background script says to proceed. Mouse gestures won't work because the data:uri frame isn't getting injected, but the iframe will display the context menu properly now.

**Comment by myfonj** [comment]
Great, thanks!
