### ISSUE TITLE
Request: Diagonal gestures

### ISSUE THREAD

**Issue by Praxis-Prion** [marklieberman/foxygestures#194]
Is it possible to add support for diagonal gestures? Years of using Mouse Gestures Redox has trained me to use some gestures diagonally, which is not possible anymore since it is no longer supported. For example, I would use down-right to close tab, but in Foxy Gestures I have to gesture either down and then right, or right and then down. I've been working around this by using another addon, Mouse Gesture Events, on top of Foxy Gestures for the use of diagonal gestures, but having both of these addons in place sometimes causes issues, such as both of them registering the close tab gesture and then closing 2 tabs at once.

Thank you! I really like Foxy Gestures!

**Comment by marklieberman** [comment]
I'll plan to add a toggle to enable diagonal gestures in the near future, but it will be low priority. There are a number of more pressing features to support first. However, I have been thinking about it for a while so I do want to implement it.

**Comment by Dakyne** [comment]
Any news ? I would love to see this **ツ**

**Comment by marklieberman** [comment]
I was stuck in the chemo clinic today so I decided to see what I can do in 2 hours to implement this. I added support for diagonals, but I feel that the experience isn't very great yet. 

I started by dividing the coordinates into 45deg segments pointing in each direction UDLR and diagonals. I find it hard to be accurate unless you move very slowly. I just naturally seem to end up on the edge of two segments when drawing and I get something like LuULu. Changing directions is also difficult to do consistently.

![image](https://user-images.githubusercontent.com/6473247/41384135-2679e6c4-6f42-11e8-91e0-0332ad6b3e10.png)

I think it might be better to make the UDLR segments only 30deg and the diagonals 60deg since its hard to draw diagonals consistently.

If anyone wants to play with this, checkout `feature/intercardinal`. Diagonals can be enabled using Gesture Style dropdown in the general settings tabs.

**Comment by marklieberman** [comment]
This has been implemented. To enable diagonal gesture, go into the General Settings tab of the Options page and choose a gesture style.
![image](https://user-images.githubusercontent.com/6473247/41876230-26ec7858-789b-11e8-8fcb-961910ce17f5.png)
Once you choose a intercardinal gesture style, you can use diagonal gestures to assign built-in commands like so:
![image](https://user-images.githubusercontent.com/6473247/41876328-703d9046-789b-11e8-9e2d-3b059289d884.png)
If anyone is willing to checkout master and do some additional manual QA on this feature that would be great. 

One significant change is that gestures need two consecutive movements in the same direction to register a change. You shouldn't really notice this, but if you drift a bit during a gesture you are less likely to get something like LuLLu.
