### ISSUE TITLE
Fix context menu when using wheel gesture to reload a page

### ISSUE THREAD

**Issue by marklieberman** [marklieberman/foxygestures#21]
The context menu isn't suppressed on mouse up when a wheel gesture is used to reload the tab. This used to be covered by 83051d6862217bd5e0fb6fb410d3fdc385bb5119 but that caused problems for framed pages.

**Comment by victorhcm** [comment]
Have you already shipped this patch to addons.mozilla.org? I've just tried it, and the context menu still is opening after gestures in mine (Firefox 57.0a1).

Btw, thank you for this great work! :smile:

**Comment by marklieberman** [comment]
I've submitted version 1.0.7 to AMO for review, so it should appear in a few days.

**Comment by marklieberman** [comment]
@victorhcm I just got the notification that 1.0.7 was approved on AMO. Please let me know if you continue to experience problems with wheel gestures. Thanks.

**Comment by victorhcm** [comment]
Thanks, @marklieberman! 

I've just tried, but it still is happening for the gestures I tried (back, forward, close tab, reload). To make sure, I double-checked if the version I'm using is 1.0.7. In your tests, does it suppress for which gestures?

I just read this warning in your extension page:

> OSX/Linux users:
When the gesture button is set to "Right", the context menu is not prevented. This is due to https://bugzilla.mozilla.org/show_bug.cgi?id=1360278. The next version of Foxy Gestures will include some features to work around this limitation until a patch can be contributed to Firefox.

Let's hope it will be fixed in the near future :blush:

**Comment by marklieberman** [comment]
@victorhcm Oh sorry, I thought you were a Windows user getting the context menu due to a specific bug related to wheel gestures. Yes, it is unfortunate about that bug for Linux/OSX. I'd like to make a patch for it myself eventually, but I don't have much experience with compiling Firefox so I have a lot to learn first.

**Comment by victorhcm** [comment]
It was my fault, I should have said it before. Thank you for your attention, @marklieberman
