### ISSUE TITLE
send a referer to a new tab opened with "Open Link in New Background Tab"

### ISSUE THREAD

**Issue by shinji2009** [marklieberman/foxygestures#246]
hi
it is possible to open a new tab with "Open Link in New Background Tab" with a referer with 1st level domain of site opened from? (like www.site.som) (configurable) because there is some sites that are not working properly if their links opened without their referer.
thanks.

**Comment by marklieberman** [comment]
There is no way to set headers using tabs.create() API when creating a new tab. It could possibly be done with webRequest APIs to modify the request being loaded in the new tab. It would be messy, and I'm not willing to add the webRequest permission to the addon just for this case. 

I'm not sure if there is a simpler way, but off the top of my head I'd do it like this: Write a very simple addon that just listens for a message containing the URL you want to load using runtime.onMessageExternal. Then have FG send a message to your addon with a userscript, and your addon creates a new tab and injects the referrer header.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest

**Comment by marklieberman** [comment]
@shinji2009 I was messing around to see if there was another way to set the referrer and I have this hacky user script solution but its not that great. The biggest problem is that by trying to open a link using window.open() or element.click() triggers the Firefox popup blocker. If you allow popups, then it works and opens the page but there is a flash because instead of opening in the background it opens in the foreground and then the current tab is set back to the original tab.

```js
if (data.element.linkHref) {
    // GEt the ID of the currently active tab.
    executeInBackground(() => browser.tabs.query({ currentWindow: true, active: true }).then(tabs => tabs[0].id)).then(currentTab => {
        // Open the link in a new window. This triggers the Firefox popup blocker.
        window.open(data.element.linkHref);
        
        // Activate the current tab again after opening the window.
        executeInBackground(currentTab => browser.tabs.update(currentTab, { active: true }), [ currentTab ]);
    });
}
```

**Comment by shinji2009** [comment]
wow its working thank you!!
