### ISSUE TITLE
"Save Media As" gesture truncating file name at non-alphanumeric character if "." exists in string before

### ISSUE THREAD

**Issue by rndm6779933732** [marklieberman/foxygestures#261]
This bug was introduced in version 1.2.0. The "Save Media As" gesture worked correctly in versions below 1.2.0.

Examples as follows:

Filename: string01.string02_string03.jpg
Expected file name when saving: string01.string02_string03.jpg
Resulting file name when saving: string01.string02

Filename: string01.string02-string03.jpg
Expected file name when saving: string01.string02-string03.jpg
Resulting file name when saving: string01.string02

Note that using Firefox's "Save Image As..." right click menu function saves the filename correctly

**Comment by marklieberman** [comment]
Probably introduced by #251.

**Comment by rndm6779933732** [comment]
Thanks for the quick reply. That is quite interesting.

However, as noted, this particular issue only started from version 1.2.0. If it was due to a change for #251, perhaps it could be reverted?

As for #251, just a note. Firefox seems to "solve" the invalid character as follows, from the example given:

https://pbs.twimg.com/media/Deh3bIAXUAAfyxP.jpg:large

Firefox removes the invalid character, then re-adds the file extension so the filname becomes

Deh3bIAXUAAfyxP.jpg large.jpg

Final note: Gesturefy seems to handle this issue correctly. With #251, Gesturefy incorrectly handles the filename in the example as:

Deh3bIAXUAAfyxP.jpg large.jpg large

**Comment by marklieberman** [comment]
The thing is Firefox knows its a JPG because it can see the image data. So for FF its trivial to strip the characters and add back the .jpg extension.

The image type isn't known to me in JavaScript which is why I have code to try to extract the filename and extension from the URL. I don't actually know the extension until I parse it, and parsing it is complicated by adding junk to the end. The regex I used in #251 is just too conservative because it assumes only one . in the filename.

I believe the most accurate filename to use is just Deh3bIAXUAAfyxP.jpg, because even FF's name of "Deh3bIAXUAAfyxP.jpg large.jpg" seems weird to me.

**Comment by rndm6779933732** [comment]
I agree. Firefox's solution makes the filename weird. However, at the very least, the user does not have to wonder what type of file it is.

I understand the difficulty of using regex. I appreciate all the hard work you've put into this extension. It's not an "end of the world" problem. For now, the solution would seem to be having to use Firefox's right click menu option. It was extremely handy to have that option in Foxygestures, and I hope you can find a solution.

Thank you again!

**Comment by marklieberman** [comment]
I rewrote the filename guessing code and even added units tests. I will make a release to AMO within a few days time.
