### ISSUE TITLE
Duplicate tab in background

### ISSUE THREAD

**Issue by BubiBalboa** [marklieberman/foxygestures#277]
Hi! Could you please add the option to duplicate the current tab in a background tab? 

Right now the tab is duplicated in the background at first but as soon as the new tab is completely loaded FF switches to the new tab. That means there are situations where you execute the gesture, continue working in the tab only to get switched to the new tab a few seconds later while you are doing something else. 

Thanks for this awesome add-on!

**Comment by marklieberman** [comment]
I will add a built-in command for this. In the meantime, you can use the following user script.

Note that there is a web extension API `tab.duplicate()` that copies the history and such of the tab. However, there is no option to duplicate in the background. 

This following script creates a new tab with the same URL but there is no tab history so its not a true duplicate. However, it avoids a flickering because I do not have to switch the active tab back after duplicating.

__Duplicate Tab in Background__
```js
executeInBackground(() => {
    browser.tabs.query({ currentWindow: true, active: true }).then(tabs => {
        let tabOptions = {};
        tabOptions.url = tabs[0].url;
        tabOptions.active = false;
        tabOptions.openerTabId = tabs[0].id;
        // Preserve the container when opening a new tab from a link/frame.
        tabOptions.cookieStoreId = tabs[0].cookieStoreId;
        if (settings.insertRelatedTab) {
          tabOptions.index = tabs[0].index + 1;
        }
        return browser.tabs.create(tabOptions);
    });
});
```

If you need to have a true duplicate tab, you can use this version of the script. However, the active tab will flicker which may be annoying.
```js
executeInBackground(() => {
    return browser.tabs.query({ currentWindow: true, active: true }).then(tabs => {
        return browser.tabs.duplicate(tabs[0].id).then(() => {
            browser.tabs.update(tabs[0].id, { active: true });
        });
    });
});
```

**Comment by BubiBalboa** [comment]
Thank you for your help! I tried the first script as tab history shouldn't be an issue most of the time and it works flawlessly.
