### ISSUE TITLE
Request: Toggle Sidebar on/off

### ISSUE THREAD

**Issue by SixthStreet** [marklieberman/foxygestures#284]
Either specific sidebar or the currently open one.  Can a user script be written for it?

**Comment by marklieberman** [comment]
Unfortunately, it isn't currently possible to open a sidebar because of several API limitations.

The first is that an extension may only open its own sidebar.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/open

The second is that mouse gestures do not have the "user input" attribute due to async communication within the addon code.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions
