### ISSUE TITLE
Save media as/now saves some images without extension (and original filename)

### ISSUE THREAD

**Issue by Guttts** [marklieberman/foxygestures#292]
Some images are downloaded as a file named "download". It adds a counter if there already is such file, but it doesnt give it any extension. It doesnt retain the actual filename, but the no extension is a bigger problem. RMB-save image as works fine. 
Is there a way in this addon or firefox itself to fix it? Or at least something like if there is no extension, give it .jpg?

**Comment by marklieberman** [comment]
If you can provide me an example to test I may be able to debug this. However, this usually caused by URLs that do not have a file name but instead use HTTP headers to tell Firefox the name and type of file it is. Since web extensions do not have access to HTTP headers during the download it is not possible for FG to determine the correct name or file type.

**Comment by Guttts** [comment]
example 1 - Twitter. No extension. [https://twitter.com/SamTalksTesla/status/1313208528425820161/photo/1](url)

example 2 - TFW2005 forum. Some work, but most make filename "download" and no extension. For example the first image on this page, post number 41. [https://www.tfw2005.com/boards/threads/if-iron-factory-appreciation-thread.1184749/page-3/](url)

**Comment by marklieberman** [comment]
Example 1)
The URL does not have an extension on the filename. Firefox itself knows its a JPG because of the content-type header. FG cannot see that header and there is no way to query mime type from the img tag.

Example 2) The images in that forum are served using content disposition header. There is no way for FG to get that information, only Firefox can know it.

There is a potential workaround for both by doing HEAD requests to get those headers without actually starting a download, but that has its own issues and may cause other problems. Nevertheless I am going to see about implementing it to cover these cases where the filename cannot be guessed from the URL.

**Comment by Guttts** [comment]
Thank you. Its not a blocker, but its tedious to rename everything manually and until I do the thumbnails in file browser dont work and such.
