### ISSUE TITLE
Support for mouse wheel gestures

### ISSUE THREAD

**Issue by gaberad** [marklieberman/foxygestures#3]
Hi, do you plan/is it possible to have mouse wheel gestures like in firegestures?

Specifically I'm thinking of the Popup options firegestures had, for things like history and recently closed tabs list (may be better to track popups as a separate issue?)

Not sure if the latter is possible in web extensions, I might have a play around and test if it's possible.

**Comment by marklieberman** [comment]
I don't use mouse wheel gestures myself so I had to go enable them in FireGestures to try it out. I think I can support gesture button + scroll pretty easily.

Popups is a little more involved. I will keep it in mind as a feature when I implement #2 since both will have to do similar DOM manipulations.

**Comment by marklieberman** [comment]
Wheel gestures feature is nearly done but it was more complicated than expected. Basically, its easy to implement wheel gestures in a given tab but more difficult if the gesture changes or reloads the active tab.

The problem is that the gesture state in each tab is totally isolated from other tabs. Consider the Next Tab command bound to scroll up. Mouse down followed by scroll up happens in the current tab, but mouse up and contextmenu happens in the next tab.

First thing I did was always prevent the context menu from appearing if there was no mouse down.

Second thing was a little more involved. I made the gesture state in each tab partially serializable so it could be replicated to other tabs. The Next Tab command - only when called by a wheel gesture - replicates the gesture state to the next tab. This lets you continue scrolling to repeat the Next Tab command.

I'm going to spin off popups into a separate issue.
