### ISSUE TITLE
Add a 'real' PageUp/PageDown gesture

### ISSUE THREAD

**Issue by rubcap** [marklieberman/foxygestures#38]
The 'PageDown' gesture now increments the page number in the URL.
Very neat and useful, but not what I was expecting when I read 'PageDown'.
'NextPage' could be a better naming for this feature?

On the other hand, a real 'PageDown' gesture would enable us to scroll the page to the next viewport, much like when you hit the space bar on a website. FireGestures had this feature and I used it a lot.

The same goes for 'PageUp' of course ...

**Comment by marklieberman** [comment]
I will add the feature to scroll the viewport for you. However, for consistency I think it will be called "Scroll Up/Down" since it matches "Scroll to Top/Bottom" which both move the viewport. "Page Up/Down" refers to paginated content. If you do a localization you are of course free to name the commands as you wish.

Also, the tooltip for "Page Down" should say "Decrement the page number...". That is a copy-paste error that I didn't notice until now.
