### ISSUE TITLE
Provide a way to call the inbuilt gestures from user scripts

### ISSUE THREAD

**Issue by grssam** [marklieberman/foxygestures#40]
I would like to , for instance, be able to have a custom rule based media saving user script, which finally falls back to the default behavior of "save media as" gesture in case my rules did not satisfy.

This is just a simple example, the possibilities are endless.

**Comment by marklieberman** [comment]
You can just invoke the built in commands directly, because they are in-scope of user scripts. The only thing to be aware of is that commands are split into two groups. The user script is running in the unprivileged "content" side in which all commands from "content/commands.js" are in scope. To use commands which require access to privileged APIs such as those in "background/commands.js", do so like the following example:

```
executeInBackground((data) => {
    commandSaveMediaAs(data);
}, [ data ]);
```

**Comment by grssam** [comment]
Ah, thanks. This should work.
