### ISSUE TITLE
"Save Media As" doesn't remember directory by domain

### ISSUE THREAD

**Issue by josefGme** [marklieberman/foxygestures#41]
When I use the context menu to save for example an image, then firefox remembers the target directory for media from the same domain and starts navigation for the next image from the same domain in that directory.
When I use the gesture the "Save as" dialog always starts with the "Downloads" directory and doesn't remember the last directory.

**Comment by marklieberman** [comment]
The [downloads](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download) API does not seem to remember any paths. Also, you cannot specify a folder without also providing a filename.

In order to make it remember the last used directory per domain I would have to write it all myself (parse the download URL to determine filename and remember the paths per domain) and it would be decoupled from the context menu's "Save Image As..." option.

It might be a better solution to post on BugZilla about making the downloads API able to remember the paths.

**Comment by grssam** [comment]
maybe, one short term hacky solution would be to simply put the url up for download and let the browser handle it... I am not sure if that's possible at all though..

**Comment by marklieberman** [comment]
I didn't get much response on Mozilla IRC so I've gone ahead and logged an issue on BugZilla. https://bugzilla.mozilla.org/show_bug.cgi?id=1395207. Lets wait and see what they have to say before proceeding.

**Comment by josefGme** [comment]
Thank you very much for your efforts.

**Comment by marklieberman** [comment]
@josefGme @grssam The bug got classified as P5 so I do not expect a resolution anytime soon. Let me suggest a workaround for the moment. 

In the [User Scrips](https://github.com/marklieberman/foxygestures/wiki/User-Scripts) wiki article there is an example script called "Pattern Matching Quick Save". You use this script and setup rules for your most common domains. For example:
```js
rules.push({ name: 'DeviantArt', regex: /deviantart\.com/i, target: 'DeviantArt/%F%' });
```

Then you bind the user script to a gesture, and any files downloaded from deviant.com via that gesture will be automatically saved in &lt;Downloads&gt;/DeviantArt. Just make sure to have a catch-all rule at the bottom of the list or rules.

**Comment by grssam** [comment]
The API feature was merged to mozilla central 10 months ago and is now present in latest release as well.
