### ISSUE TITLE
Always active gesture state

### ISSUE THREAD

**Issue by ZoidbergForPresident** [marklieberman/foxygestures#44]
Sometimes and/or on some pages, the gesture state is always active and registering gestures and thus makes the feature unusable.

**Comment by marklieberman** [comment]
Can you tell me some details like:
1) What edition of Firefox are you using: release, dev, or nightly?
2) What pages or websites is this happening on most often?
3) Are you often doing anything before it happens like a particular mouse or wheel gesture?
4) Anything else you can think of to help me reproduce the issue?

**Comment by marklieberman** [comment]
Can you try version 1.0.8beta1 from my development channel and tell me if it fixes the "stuck on" gesture problem? https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/versions/beta I found a bug in wheel gesture code that could cause that type of issue.

**Comment by ZoidbergForPresident** [comment]
Strange, gestures seem to not work at all with this version.

I'm using 55.0.3 64bits.

**Comment by marklieberman** [comment]
It does not appear to be fixed. I was finally after a ton of trying able to reproduce the problem semi-reliably. Standby, I will keep debugging it and post another beta.

**Comment by marklieberman** [comment]
@ZoidbergForPresident I just published 1.0.8beta4 which I am very confident will fix the issue. Please try it out for me, thanks.

The problem is caused by using wheel gestures with Next Tab or Previous Tab commands. There is a whole sequence of events to make it so that wheel gestures keep working as you scroll through tabs. (Normally, tabs are isolated so one tab doesn't know a gesture was started in another tab.) 

To reproduce the problem, you need to generate 2 or more wheel events before the next tab can get activated. If you did this, the tab two spaces over gets activated, but the tab one space over was bugged and left the gesture "activated."

**Comment by ZoidbergForPresident** [comment]
Cool I'll check it out.

Glad I could "help" :P

**Comment by marklieberman** [comment]
@ZoidbergForPresident Grab it here https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/versions/beta

**Comment by ZoidbergForPresident** [comment]
Cheers!

Oh and the tab scroll feature was scrolling between the tabs by scrolling the mouse wheel.

I don't know if it's doable with the new way of making addons.

**Comment by marklieberman** [comment]
Unfortunately, web extensions do no have access to that part of the browser. I did find this bug on Bugzilla to implement that feature. https://bugzilla.mozilla.org/show_bug.cgi?id=1285812 Doesn't seem like the devs are too keen on making it happen however.
