### ISSUE TITLE
Latency when grabbing screen on Google Street View

### ISSUE THREAD

**Issue by mathew832** [marklieberman/foxygestures#52]
Just a mildly annoying issue. Left-click to drag the 360 view doesn't take effect until almost a second so sometimes you're clicking and dragging and nothing happens until your cursor is most of the way across the screen. Maybe you can mitigate this issue by giving an option to totally disable left-click features since many people, as myself, don't use them, only right-click for gestures. 

OS: Windows 10 Creator's Edition
Firefox Version: Nightly 57 9-13-17

Thanks for your work.

**Comment by marklieberman** [comment]
There are no left-click features in Foxy Gestures at this time unless you set your gesture button to left. Also, the listeners for mousedown and mouseup are very light, and the mousemove handler returns immediately if there is no gesture in progress. Lastly, I am not encountering any slowdown when using Street View in Google Maps on Nightly.

**Comment by mathew832** [comment]
It's not a slowdown issue, it's latency when grabbing the Streetview image and rotating. It only happens with the extension enabled. It seems the extension listens for mousedown gestures and defaults to normal grab/drag on the site almost a second after mousing down. I thought I'd try to reproduce this on youtube 360 videos, can't think of any place else that has that feature. But I can't view 360 videos correctly as I'm getting a webgl error in about:support, which I don't think is related.

**Comment by marklieberman** [comment]
A one second latency is unnatural. The heaviest function call done in the mouse down handler is [getMouseData](https://github.com/marklieberman/foxygestures/blob/5b0bb56707c4afe6b6f7fc64e81cbe5ff30ff5ba/src/content/mouseEvents.js#L113) to collect some DOM required by the commands down the line. That function calls [findLinkHref](https://github.com/marklieberman/foxygestures/blob/5b0bb56707c4afe6b6f7fc64e81cbe5ff30ff5ba/src/content/helpers.js#L70) which iterates up the DOM but the number of iterations is bounded. That is potentially where the time is spent, but it doesn't take more than a couple milliseconds to seek up a few nodes. I don't believe this is the issue, or it would feel laggy for all clicks.

I've tested Foxy Gestures two machines and I do not experience any noticeable lag on Google Maps. I tried Win 10 w/ Nightly and OSX with 55. I also tried it on some other sites like https://www.360cities.net/, http://ivrpa.org/panoramas/ (uses YouTube), https://pannellum.org/, http://photo-sphere-viewer.js.org/, and http://www.marzipano.net/demos/sample-tour/index.html.

Perhaps you could paste a link to Google Maps so that I could open up the exact same page as you?

**Comment by mathew832** [comment]
I tested with a VM, lag all around so can't say there but still have lag in Windows 10 on Nightly. It's a mouse-down type of lag. If I hold the mouse down for a second, grab and move, I get no apparent lag. It's only in the mousing down and grabbing that it seems to lag. 

But [here](https://www.google.com/streetview/#this-is-home/outside-a-mongolian-yurt-ger) you go, that's just a default Streetview link where it exhibits the problem. Thanks for investigating. If I wasn't sure it was an extension issue, I wouldn't waste your time with this.

**Comment by marklieberman** [comment]
I only experience a bit of lag when I set `extensions.webextensions.remote` to false. If you've set it to false previously, use 1.0.8beta6 and set it back to true. Otherwise, I don't experience any input lag.

**Comment by mathew832** [comment]
Thanks. I updated to 1.0.8beta6 and it seems better now. Still just a little bit of latency but not a big deal.

**Comment by marklieberman** [comment]
Closing for now, but will re-open if you have any new information.
