### ISSUE TITLE
Improve gesture interactions when using left mouse button

### ISSUE THREAD

**Issue by WhoWouldaThunk** [marklieberman/foxygestures#53]
It doesn't work very well with the left mouse button as the browser still seems to be trying to use the default actions when you left click, on top of the extension attempting to draw a mouse gesture. For instance, you can't open links using mouse gestures as it just grabs the url to drag and drop it. Or, when it's over an image, you can't initiate a gesture to close the page.

**Comment by marklieberman** [comment]
I tried a few things and here's some notes: by cancelling the dragstart event I can prevent drag-and-drop from interrupting the gesture. However, you will be unable to initiate normal drag-and-drop. By cancelling the selectstart event I can prevent text from being selected in the page during a gesture. However, you will be unable to select text normally. Being unable to select text is particularly bad. 

I need to look again how FireGestures handles this, because I am not sure if I can copy that behaviour exactly.

**Comment by WhoWouldaThunk** [comment]
Firegestures doesn't do it properly either as it has the same issue. The only one that does, that I know of, is all in one gestures. But, they also allow you to bypass the mouse gestures by holding a modifier (alt) so that the normal browser behaviour resumes. Personally, I never drag and drop anything, so that wouldn't make a difference to me. But, you might run into issues clicking buttons etc...if there's no way to suspend the mouse gesture when needed.
