### ISSUE TITLE
Backup settings broken in OSX (maybe Linux) due to internal Firefox issue

### ISSUE THREAD

**Issue by imkc1127** [marklieberman/foxygestures#60]
Clicking the "Download Settings" button opens a blank page and loading forever.   

All other extensions have been disabled and Firefox (v55.0.3) has been restarted before the download action.  There should be nothing conflicting with the FoxyGestures.

Screen capture (gif):   https://pixhost.org/show/164/52311115_170923_foxygesturesbackup.gif

**Comment by marklieberman** [comment]
It's working for me on Windows, but fails in OSX. I'll have to find another way to trigger a file download in JavaScript.

**Comment by imkc1127** [comment]
After upgrading to Firefox 56.0, the Backup function now works.
Thanks for your time.

**Comment by marklieberman** [comment]
Unfortunately, it still seems to be broken in 56 on OSX.

**Comment by marklieberman** [comment]
I've created an issue on BugZilla because I cannot seem to get URL.createObjectURL to work on OSX. The browser is doing very strange things like hanging tabs, or closing the tab/window when attempting to open the blob URL. I'm positive there is an internal issue in Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=1404202

**Comment by marklieberman** [comment]
Changed the implementation after seeing how its done in uBlock to hopefully avoid this FF issue alltogether. https://github.com/gorhill/uBlock/blob/master/src/js/settings.js#L107
