### ISSUE TITLE
Wheel gesture is sticky if gesture ends with mouse not over DOM

### ISSUE THREAD

**Issue by Matthewus** [marklieberman/foxygestures#61]
Hi!
Sometimes if i use right click + wheel gesture and irelease the mouse button, the gesture stays active until i right click again. I use the gesture to change tabs. Am i doing something wrong or is there a setting that i can use to get rid of this problem?

**Comment by marklieberman** [comment]
Does the gesture get stuck in the tab you switched to, or the tab you switched from?

**Comment by Matthewus** [comment]
Scrolling the wheel keeps swtiching tabs until i right click, i can scroll trough every tab i have open, i just have to right click doesn't matter on which tab.

**Comment by marklieberman** [comment]
There is a dead time when switching tabs where Foxy Gestures cannot receive mouse events. It is a limitation of web extensions. I will try to add additional checks to the wheel event to see if the right button is still pressed.

**Comment by marklieberman** [comment]
I think I know how you're doing it. Do this: use a wheel gesture to change tabs, but before you release the right button, move the mouse outside the page inside the tab. It can be over the address bar or outside the Firefox window. Since the cursor is outside of the tab, the addon never receives a mouse up event from the HTML document.

**Comment by Matthewus** [comment]
Yes, i can reproduce it now.
