### ISSUE TITLE
Disable gestures on a per-site basis

### ISSUE THREAD

**Issue by qacha** [marklieberman/foxygestures#81]
It would be nice if I could disable gestures on a handful of sites manually, for pages which actually use right click + drag themselves.

**Comment by marklieberman** [comment]
How about a modifier key to disable gestures? See #10

**Comment by qacha** [comment]
That works well when you only want a few right click + drags to pass through to the client, but gets a bit cumbersome when you want it all the time (imagine a game that makes heavy use of drags with both buttons).

I'll try to take a look at the code; would you be willing to take a look at a pull request if I find the time to implement this?

**Comment by marklieberman** [comment]
I will consider a pull request, sure. However, look at `feature/chord-gestures` branch as it is very close to being merged.

**Comment by potchin** [comment]
+1 for this. I'm having to open another browser to be able to use some sites (eg tinkercad.com)

**Comment by marklieberman** [comment]
@qacha Have you made any progress on a PR or would you like me to implement this?

**Comment by superduperuser** [comment]
@marklieberman I'm not the OP, but I would really appreciate it if you implemented this feature. In addition to @qacha's points, a blacklist would fix sites that the addon is currently incompatible with. For example, I currently have FoxyGestures off because a 2F authentication system my school uses is incompatible with it. If the addon is activated, the auth page just continually refreshes until I am locked out of the system. I would love to just add the authentication site to a blacklist and continue to use FG on other sites.

**Comment by zieren** [comment]
+1 for this feature. I use the right mouse button on lichess.org for drawing arrows etc. on the chessboard, and this triggers gestures. It's especially bad in a running game when it's a left arrow and I navigate away from the game.
