### ISSUE TITLE
Gestures doesnt work on build in firefox pages

### ISSUE THREAD

**Issue by Diphal** [marklieberman/foxygestures#85]
Hi, gestures doesn't work on built-in Firefox pages like options, addons, new tab, etc. It makes it impossible to close them with gesture, or move to next or previous tab. Makes it kinda annoying to deal with those pages especially new tab which is used a lot.

Other than that your addon is GREAT! :) Thank you for your work.

**Comment by jdreesen** [comment]
See
- https://github.com/marklieberman/foxygestures/issues/64
- https://github.com/marklieberman/foxygestures/issues/58
- https://github.com/marklieberman/foxygestures/issues/23
- etc.
- and the README:
**Limitations**
As a web extension, this add-on will never be as powerful as FireGestures. This extension does not integrate into about:home, view-source:, etc. Nor will it work on addons.mozilla.com, since web extensions are forbidden from interacting with the add-on store.

**Comment by Diphal** [comment]
I see. Another reason to stay on FF 56 wehre everything works well - before they screwed it up. Thx for reply anyway.

**Comment by zhanglongqi** [comment]
@Diphal They do getting faster at new version. try it.
