### ISSUE TITLE
Mouse gesture shouldn't start unless mouse moves enough pixels after mouse down

### ISSUE THREAD

**Issue by zsau** [marklieberman/foxygestures#86]
In the latest beta (1.0.9b3) on Linux, opening links using the built-in FF middle-click gesture is now harder when middle-click is set as the gesture button. I think what's happening is that FG eats the input if I accidentally move the mouse even a few pixels before release.

**Comment by marklieberman** [comment]
Yes, this is an issue I noticed as well during my testing as well. There's some code in handler.js that throttles mouse events by pixels moved so that 1 or 2 pixel movements don't change the gesture direction. That throttling logic needs to be pushed down into mouseEvents.js so that a gesture won't trigger until the mouse moves enough pixels.

**Comment by marklieberman** [comment]
I published 10.9beta5 that fixes this issue. A gesture won't start until the mouse moves 10 pixels from its starting position. Try it out and let me know. If there are no further issues I want to release 1.0.9. Thank you.

**Comment by zsau** [comment]
It's working well in my testing. Thanks!
