### ISSUE TITLE
"This add-on has been removed by its author."

### ISSUE THREAD

**Issue by monk-time** [marklieberman/foxygestures#91]
https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/

What has happened? The extension was available just a few days ago, but now AMO says it has been removed.

**Comment by marklieberman** [comment]
AMO disabled all my versions back to April over the weekend so rather than allowing people to install old versions or otherwise get confused, I temporarily set it invisible. I just got the message that it has been restored so it will be unhidden shortly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
